# Generated by Django 2.2.6 on 2019-11-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='imei',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='serial',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
